name: Deploy Laravel Backend

on:
  push:
    branches:
      - hmg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
          coverage: none

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HETZNER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Backend
        run: |
          rsync -avz --delete \
            --exclude='.env' \
            --exclude='.git' \
            --exclude='storage/framework/cache/*' \
            --exclude='storage/framework/sessions/*' \
            --exclude='storage/framework/views/*' \
            --exclude='storage/logs/*' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.HETZNER_HOST }}:/var/www/backend/

      - name: Post-deployment tasks
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HETZNER_HOST }} '
            cd /var/www/backend && \
            php artisan migrate --force && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache
          '
